sudo: required
services:
  - docker

before_install:
  - docker build -t yashgarodiya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yashgarodiya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-370663139893'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
